/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package vision.IndexingImagenes;

import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.DataInputStream;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Enumeration;
import java.util.Hashtable;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import java.util.Comparator;

/**
 *
 * @author juanagva
 */
public class FrameBuscar extends javax.swing.JFrame {

    /**
     * Creates new form FrameBuscar
     */
     JFileChooser fc = new JFileChooser();
     String foto = new String();
     Hashtable listaImagenesPesos  = new Hashtable();
     Hashtable listaImagenesPesosFinal  = new Hashtable();
      ArrayList listaImagenes = new ArrayList();
      
    public FrameBuscar() {
        initComponents();
    }
    
    
      static List<String> lista = Arrays.asList("Auto Color Correlogram","CEDD Document","Color Histogram","Color Layout",
      "Default Document","Edge Histogram"
        ,"FastAutoColorCorrelation","FCTHD","GaborDocument","JCDDocument","JpegCoefficientHistogramDocument"  
        ,"ScalableColor","TamuraDocument");
   
    
   
    

    public void setjComboBox1(List<String> lista) 
    {
        this.jComboBox1.removeAllItems();
        for(String item : lista )
        {
           this.jComboBox1.addItem(item); 
        }
        
    }  
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Elegir la ubicacion de la imagen");

        jButton1.setText("Elegir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText(" ");

        jButton3.setText("Analizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jButton3))
                    .addComponent(jLabel2)
                    .addComponent(jButton1)
                    .addComponent(jLabel1)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         int returnVal = fc.showOpenDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
             foto  = fc.getSelectedFile().toString();
             this.jLabel2.setText(foto);            
           
        } else {
            System.out.println("no se selecciono ningun directorio");
        }  
        
        this.setjComboBox1(lista);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       
        ImagenBusqueda busqueda = new ImagenBusqueda();
        
         try 
         {
              FileInputStream imageStream = new FileInputStream(foto);
              BufferedImage bimg = ImageIO.read(imageStream);
        
             
                String opcion = this.jComboBox1.getSelectedItem().toString();
                if (opcion.equals("Auto Color Correlogram"))
                {
                    busqueda.setIndexPath("Auto-Color");
                      listaImagenes =  busqueda.testSearchAutoColorCorrelogram(bimg);
                }
                if (opcion.equals("CEDD Document"))
                {
                    busqueda.setIndexPath("CEDD-Document");
                      listaImagenes =  busqueda.testSearchCEDD(bimg);
                }
                if (opcion.equals("Color Histogram"))
                {
                    busqueda.setIndexPath("Color-Histogram");
                      listaImagenes =  busqueda.testSearchColorHistogram(bimg);
                }
                 if (opcion.equals("Color Layout"))
                {
                    busqueda.setIndexPath("Color-Layout");
                    listaImagenes = busqueda.testSearchColorLayout(bimg);
                }
                  if (opcion.equals("Default Document"))
                {
                    busqueda.setIndexPath("Default-Document");
                     listaImagenesPesos = busqueda.testSearchDefault(bimg);
                }
                   if (opcion.equals("Edge Histogram"))
                {
                    busqueda.setIndexPath("Edge-Histogram");
                      listaImagenes = busqueda.testSearchEdgeHistogram(bimg);
                } 
                 if (opcion.equals("FCTHD"))
                {
                     busqueda.setIndexPath("FCTHD");
                      listaImagenes =  busqueda.testSearchFCTH(bimg);
                } 
               
                 if (opcion.equals("GaborDocument"))
                {
                     busqueda.setIndexPath("GaborDocument");
                      listaImagenes =  busqueda.testSearchGabor(bimg);
                }   
                 if (opcion.equals("JCDDocument"))
                {
                    busqueda.setIndexPath("JCDDocument");
                     listaImagenes =   busqueda.testSearchJCD(bimg);
                }
                  if (opcion.equals("JpegCoefficientHistogramDocument"))
                {
                     busqueda.setIndexPath("JpegCoefficientHistogramDocument");
                     listaImagenes =   busqueda.testSearchCoefficientHistogram(bimg);
                }
                   if (opcion.equals("ScalableColor"))
                {
                     busqueda.setIndexPath("ScalableColor");
                      listaImagenes =  busqueda.testSearchScalableColor(bimg);
                }
                   
                    if (opcion.equals("TamuraDocument"))
                {
                    busqueda.setIndexPath("TamuraDocument");
                     listaImagenes =   busqueda.testSearchTamura(bimg);
                }
        } 
         catch (IOException ex) 
         {
                Logger.getLogger(FrameIndexing.class.getName()).log(Level.SEVERE, null, ex);
          }
        
         
         Hashtable dicCategoria  = TablaDiccionario(); 
        String TextoArea = "";
               
               
        for (Object texto : listaImagenes)
        {
           String CategoriaDeLaImagen = dicCategoria.get(texto).toString();
           TextoArea += CategoriaDeLaImagen + "  " +  texto.toString() + " \n\r";
        }
        
        Enumeration e = listaImagenesPesos.keys();  
                Object obj;  
                   while (e.hasMoreElements()) 
                   {                        
                      obj = e.nextElement();                        
                      if(listaImagenesPesosFinal.containsKey(dicCategoria.get(obj).toString()))
                      {
                        String categoria =  dicCategoria.get(obj).toString();                        
                        float val3 = Float.valueOf(listaImagenesPesosFinal.get(categoria).toString()) + Float.valueOf(listaImagenesPesos.get(obj).toString());
                        listaImagenesPesosFinal.put(dicCategoria.get(obj).toString(),val3);
                      }
                      else
                      {
                        listaImagenesPesosFinal.put(dicCategoria.get(obj).toString(),listaImagenesPesos.get(obj));
                      }
                      System.out.println(" key "+ dicCategoria.get(obj).toString() +": "+ listaImagenesPesos.get(obj));  
                   }           
        
        float Value; 
       
         ArrayList myArrayList=new ArrayList(listaImagenesPesosFinal.entrySet());
      
         //Sort the values based on values first and then keys.
        Collections.sort(myArrayList, new MyComparator());
         
        
        this.jTextArea2.setText(TextoArea);
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public Hashtable TablaDiccionario()
    {
        Hashtable dicCategoria  = new Hashtable(); 
        try
        {
            // Open the file that is the first 
            // command line parameter
            FileInputStream fstream = new FileInputStream("Diccionario.txt");
            // Get the object of DataInputStream
            DataInputStream in = new DataInputStream(fstream);
            BufferedReader br = new BufferedReader(new InputStreamReader(in));
            String strLine;
            //Read File Line By Line
            while ((strLine = br.readLine()) != null)  
            {
                int indexComa = strLine.indexOf(",");
                String llave = strLine.substring(0, indexComa);
                String Categoria = strLine.substring(indexComa+1,strLine.length());
                dicCategoria.put(llave, Categoria);
            // Print the content on the console
            //   System.out.println (strLine);
            }
            //Close the input stream
            in.close();
         }
        catch (Exception e)
            {//Catch exception if any
                System.err.println("Error: " + e.getMessage());
            }
        
        return dicCategoria;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameBuscar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameBuscar().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    // End of variables declaration//GEN-END:variables
}
